polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('menu/', views.menu, name='menu'),
    path('criarbalancete/', views.criarbalancete, name='criarbalancete'),
    path('listarbalancetes/', views.listarbalancetes, name='listarbalancetes'),
    path('<int:balancete_id>/verbalancete/', views.verbalancete, name='verbalancete'),
    path('<int:balancete_id>/addreceitadespesa/', views.addreceitadespesa, name='addreceitadespesa'),
]

polls/models.py
from django.db import models

class Balancete(models.Model):
    Nome = models.CharField(max_length=100)
    Data = models.DateField("Data de Publicação:")
    Foto = models.ImageField(upload_to='balancetes/', null=True, blank=True)
    
class Receita(models.Model):
    balancete = models.ForeignKey(Balancete, default=0, on_delete=models.CASCADE)
    Nome = models.CharField(max_length=100)
    Valor = models.IntegerField(default=0)
    
class Despesa(models.Model):
    balancete = models.ForeignKey(Balancete, default=0, on_delete=models.CASCADE)
    Nome = models.CharField(max_length=100)
    Valor = models.IntegerField(default=0)

polls/forms.py
from django import forms
from .models import Balancete, Receita, Despesa
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label='Nome de Usuário', max_length=20)
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

class CadastroForm(forms.ModelForm):
    username = forms.CharField(
        max_length=20,
        required=True,
        error_messages={'required': '', 'max_length': ''}
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        required=True,
        error_messages={'required': ''} 
    )

    class Meta:
        model = User
        fields = ['username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    

class BalanceteForm(forms.ModelForm):
    class Meta:
        model = Balancete
        fields = ['Nome', 'Data', 'Foto']
        widgets = {
            'Data': forms.DateInput(attrs={'type': 'date'}),
        }

class ReceitaForm(forms.ModelForm):
    class Meta:
        model = Receita
        fields = ['Nome', 'Valor']
        widgets = {
            'Nome': forms.TextInput(attrs={'class': 'Nome'}),
            'Valor': forms.NumberInput(attrs={'class': 'Valor', 'min': 0}),
        }

class DespesaForm(forms.ModelForm):
    class Meta:
        model = Despesa
        fields = ['Nome', 'Valor']
        widgets = {
            'Nome': forms.TextInput(attrs={'class': 'Nome'}),
            'Valor': forms.NumberInput(attrs={'class': 'Valor', 'max': 0}),
        }

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Balancete, Receita, Despesa
from .forms import BalanceteForm, ReceitaForm, DespesaForm, LoginForm, CadastroForm
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'polls/index.html')

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('polls:menu') 
    else:
        form = LoginForm()
    
    return render(request, 'polls/login.html', {'form': form})

def logout(request):
    auth_logout(request)
    return redirect('polls:index')

def cadastro(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:login')
    else:
        form = CadastroForm()
    
    return render(request, 'polls/cadastro.html', {'form': form})

@login_required
def menu(request):
    username = request.user.username
    return render(request, 'polls/menu.html', {'username': username})

@login_required
def criarbalancete(request):
    if request.method == 'POST':
        form = BalanceteForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('polls:listarbalancetes')
    else:
        form = BalanceteForm()
    
    return render(request, 'polls/criarbalancete.html', {'form': form})

@login_required
def listarbalancetes(request):
    balancetes = Balancete.objects.all().order_by('-Data')
    return render(request, 'polls/listarbalancetes.html', {'balancetes': balancetes})

@login_required
def verbalancete(request, balancete_id):
    balancete = get_object_or_404(Balancete, id=balancete_id)

    searchquery = request.GET.get('search', '')

    receitasgeral = Receita.objects.filter(balancete=balancete)
    despesasgeral = Despesa.objects.filter(balancete=balancete)

    somareceitasgeral = sum(receita.Valor for receita in receitasgeral) or 0
    somadespesasgeral = sum(despesa.Valor for despesa in despesasgeral) or 0
    
    saldogeral = somareceitasgeral + somadespesasgeral

    receitas = receitasgeral.filter(Nome__icontains=searchquery)
    despesas = despesasgeral.filter(Nome__icontains=searchquery)
    
    somareceitas = sum(receita.Valor for receita in receitas) or 0
    somadespesas = sum(despesa.Valor for despesa in despesas) or 0
    
    saldoatual = somareceitas + somadespesas

    context = {
        'balancete': balancete,
        'receitas': receitas,
        'despesas': despesas,
        'saldoatual': saldoatual,
        'saldogeral': saldogeral,
        'searchquery': searchquery,
    }
    
    return render(request, 'polls/verbalancete.html', context)

@login_required
def addreceitadespesa(request, balancete_id):

    balancete = get_object_or_404(Balancete, id=balancete_id)

    if request.method == 'POST':
        if 'adicionarreceita' in request.POST:
            receitaform = ReceitaForm(request.POST)
            if receitaform.is_valid():
                receita = receitaform.save(commit=False)
                receita.balancete = balancete
                receita.save()
                return redirect('polls:verbalancete', balancete_id=balancete.id)
        elif 'adicionardespesa' in request.POST:
            despesaform = DespesaForm(request.POST)
            if despesaform.is_valid():
                despesa = despesaform.save(commit=False)
                despesa.balancete = balancete
                despesa.save()
                return redirect('polls:verbalancete', balancete_id=balancete.id)
    else:
        receitaform = ReceitaForm()
        despesaform = DespesaForm()

    return render(request, 'polls/addreceitadespesa.html', {
        'balancete': balancete,
        'receitaform': receitaform,
        'despesaform': despesaform
    })

polls/templates/polls/addreceitadespesa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            background-color: rgb(58, 0, 112);
            text-align: center;
        }

        p{
            font-size: 30px;
            color: rgb(238, 255, 0);
        }

        input{
            font-size: 25px;
        }
    </style>
</head>
<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 50px;">
        <i>Adicionar Receita</i> </h1>

    <form method="POST">
        {% csrf_token %}
        {{ receitaform.as_p }}
        <input type="submit" name="adicionarreceita" value="Adicionar Receita"
        style="margin-top: 35px; font-size: 25px; background-color: blueviolet; 
        color: rgb(238, 255, 0); padding: 10px; border-radius: 10px; height: auto; width: 280px; cursor: pointer">
    </form>

    <h1 style="color: blueviolet; margin: 70px 0px 20px 0px; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 50px;">
        <i>Adicionar Despesa</i> </h1>

    <form method="POST">
        {% csrf_token %}
        {{ despesaform.as_p }}
        <input type="submit" name="adicionardespesa" value="Adicionar Despesa" 
        style="margin-top: 35px; font-size: 25px; background-color: blueviolet; color: rgb(238, 255, 0); 
        padding: 10px; border-radius: 10px; height: auto; width: 280px; cursor: pointer">
    </form>

    <div style="margin-top: 50px;"></div>
        <a href="{% url 'polls:verbalancete' balancete.id %}" style="text-decoration: none; color: rgb(238, 255, 0); 
           background-color: blueviolet; padding: 10px; 
           border: 2px solid rgb(238, 255, 0); border-radius: 10px; cursor: pointer;">Voltar</a>
    </div>
</body>
</html>

polls/templates/polls/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            background-color: rgb(58, 0, 112);
            text-align: center;
        }
        p{
            font-size: 30px;
            color: rgb(238, 255, 0);
        }
        input{
            font-size: 25px;
        }
    </style>
</head>
<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 70px;">
    <i>Cadastro</i> </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Cadastrar">
    </form>
    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 40px; width: 300px; font-size: 25px; cursor: pointer;">
    <a href="{% url 'polls:login' %}" style="color: rgb(238, 255, 0); 
    text-decoration: none;">Já possui uma conta? <br> Faça Login</a></div>
</body>
</html>

polls/templates/polls/criarbalancete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            background-color: rgb(58, 0, 112);
            text-align: center;
        }
        p{
            font-size: 30px;
            color: rgb(238, 255, 0);
        }
        input{
            font-size: 25px;
        }
    </style>
</head>
<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 50px;">
        <i>Criar Balancete</i> </h1>

    <div style="margin-top: 80px;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Criar" style="cursor: pointer; margin-top: 35px; font-size: 25px; background-color: blueviolet; color: rgb(238, 255, 0); padding: 10px; border: 2px solid rgb(238, 255, 0); border-radius: 10px; height: auto; width: 120px;">
        </form>
    </div>

    <div style="margin-top: 200px;">
        <a href="{% url 'polls:menu' %}" style="text-decoration: none; color: rgb(238, 255, 0); 
           background-color: blueviolet; padding: 10px; 
           border: 2px solid rgb(238, 255, 0); border-radius: 10px; cursor: pointer;">Voltar</a>
    </div>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            background-color: rgb(58, 0, 112);
            text-align: center;
        }
    </style>
</head>
<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 70px;">
        <i>Finanças Pessoais</i> </h1>

    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 40px; width: 250px;">
        <a href="{% url 'polls:cadastro' %}" style="font-size: 50px; text-decoration: none; color: rgb(238, 255, 0);">Cadastrar</a>
    </div>
    <br>
    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 40px; width: 250px;">
        <a href="{% url 'polls:login' %}" style="font-size: 50px; text-decoration: none; color: rgb(238, 255, 0);">Login</a>
</body>
</html>

polls/templates/polls/listarbalancetes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            background-color: rgb(58, 0, 112);
            text-align: center;
        }

        th{
            font-size: 20px;
            color: rgb(238, 255, 0);
            padding-top: 10px;
            padding-bottom: 10px;
        }

        td{
            font-size: 20px;
            color: white;
            padding-top: 5px;
            padding-bottom: 5px;
        }
    </style>
</head>

<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 50px; margin-bottom: 60px;">
        <i>Lista de Balancetes</i> </h1>
    
    <table border="1" style="margin: 20px auto; width: 80%; border-collapse: collapse;">
        <tr>
            <th>Nome</th>
            <th>Data</th>
            <th></th>
        </tr>
        {% if balancetes %}
        {% for balancete in balancetes %}
        <tr>
            <td>{{ balancete.Nome }}</td>
            <td>{{ balancete.Data }}</td>
            <td>
                <a href="{% url 'polls:verbalancete' balancete.id %}"
                    style="text-decoration: none; color: rgb(238, 255, 0); font-weight: bold;
                    font-size: 20px;">Ver Balancete</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">Nenhum balancete encontrado.</td>
        </tr>
        {% endif %}
    </table>

    <div style="margin-top: 100px;"></div>
        <a href="{% url 'polls:menu' %}" style="text-decoration: none; color: rgb(238, 255, 0); 
           background-color: blueviolet; padding: 10px; 
           border: 2px solid rgb(238, 255, 0); border-radius: 10px; cursor: pointer;">Voltar</a>
    </div>

</body>

</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            background-color: rgb(58, 0, 112);
            text-align: center;
        }
        p{
            font-size: 30px;
            color: rgb(238, 255, 0);
        }
        input{
            font-size: 25px;
        }
    </style>
</head>
<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 70px;">
    <i>Login</i> </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Entrar">
    </form>
    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 40px; width: 300px; font-size: 25px; cursor: pointer;">
    <a href="{% url 'polls:cadastro' %}" style="color: rgb(238, 255, 0); 
    text-decoration: none;">Ainda não tem uma conta? <br> Cadastre-se</a></div>
    
</body>
</html>

polls/templates/polls/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            background-color: rgb(58, 0, 112);
            text-align: center;
        }
    </style>
</head>
<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 70px;">
        <i>Finanças Pessoais</i> </h1>

    <h2 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 2px 2px rgb(238, 255, 0); font-size: 30px;">
        Bem-vindo, {{ username }}!
    </h2>

    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 40px;">
        <a href="{% url 'polls:criarbalancete' %}" style="font-size: 50px; text-decoration: none; color: rgb(238, 255, 0);">Criar Balancete</a>
    </div>
    <br>
    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 40px;">
        <a href="{% url 'polls:listarbalancetes' %}" style="font-size: 50px; text-decoration: none; color: rgb(238, 255, 0);">Listar Balancetes</a>
    </div>
    <br>
    <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
    display: inline-block; padding: 5px; margin-top: 100px;">
        <a href="{% url 'polls:logout' %}" style="font-size: 30px; text-decoration: none; color: rgb(238, 255, 0);">Logout</a>
    </div>


    
    
</body>
</html>

polls/templates/polls/verbalancete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            background-color: rgb(58, 0, 112);
            text-align: center;
        }

        th,
        td {
            padding: 5px 80px;
        }

        strong {
            color: rgb(238, 255, 0);
        }

        p {
            color: white;
        }

        h2 {
            color: rgb(238, 255, 0);
            font-size: 27px;
        }

        th {
            font-size: 20px;
            color: rgb(238, 255, 0);
        }

        td {
            font-size: 20px;
            color: white;
        }
    </style>
</head>

<body>
    <h1 style="color: blueviolet; margin: 20px 0; font-family: 'Arial', sans-serif; 
    text-shadow: 2px 4px 4px rgb(238, 255, 0); font-size: 50px; margin-bottom: 60px;">
        <i>Detalhes do Balancete</i>
    </h1>

    <div
        style="border: 2px solid rgb(238, 255, 0); padding: 20px; margin: 20px auto; width: 60%; background-color: blueviolet;">

        <p style="font-size: 25px;"><strong>Nome:</strong> {{ balancete.Nome }}</p>
        <p style="font-size: 25px;"><strong>Data:</strong> {{ balancete.Data }}</p>

        {% if balancete.Foto %}
        <p style="font-size: 25px; margin-top: 15px;"><strong>Foto:</strong></p>
        <img src="{{ balancete.Foto.url }}" alt="Foto do Balancete"
            style="max-width: 400px; height: auto; margin: 15px; border: 2px solid rgb(238, 255, 0); padding: 5px;" />
        {% else %}
        <p>Sem imagem disponível.</p>
        {% endif %}

        <p style="margin-top: 15px; font-size: 30px;"><strong>Saldo Geral:</strong> {{ saldogeral }}</p>
        <p style="margin-top: 15px; font-size: 27px;"><strong>Saldo Atual:</strong> {{ saldoatual }}</p>
        <p style="font-size: 20px;">(baseado na busca realizada)</p>

        <div>

            <div style="border: 4px solid rgb(238, 255, 0); background-color: blueviolet; 
            display: inline-block; padding: 5px; margin-top: 40px;">
                <a href="{% url 'polls:addreceitadespesa' balancete.id %}"
                    style="font-size: 20px; text-decoration: none; color: rgb(238, 255, 0);">Adicionar Receita /
                    Despesa</a>
            </div>
        </div>

        <form method="GET" action="{% url 'polls:verbalancete' balancete.id %}"
            style="margin: 20px auto; text-align: center;">
            {% csrf_token %}
            <input type="text" name="search" value="{{ search_query }}"
                placeholder="Pesquisar Receita ou Despesa por nome"
                style="padding: 10px; width: 80%; max-width: 400px; border: 1px solid rgb(238, 255, 0); border-radius: 5px; margin-right: 10px;">
            <input type="submit" value="Buscar"
                style="padding: 10px; cursor: pointer; background-color: blueviolet; color: rgb(238, 255, 0); border: 2px solid rgb(238, 255, 0); border-radius: 5px;">
        </form>

        <h2 style="margin-top: 30px;">Receitas</h2>
        <table border="1" style="margin: 10px auto;">
            <tr>
                <th>Nome</th>
                <th>Valor</th>
            </tr>
            {% for receita in receitas %}
            <tr>
                <td>{{ receita.Nome }}</td>
                <td>{{ receita.Valor }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2">Nenhuma receita encontrada.</td>
            </tr>
            {% endfor %}
        </table>

        <h2 style="margin-top: 35px;">Despesas</h2>
        <table border="1" style="margin: 10px auto;">
            <tr>
                <th>Nome</th>
                <th>Valor</th>
            </tr>
            {% for despesa in despesas %}
            <tr>
                <td>{{ despesa.Nome }}</td>
                <td>{{ despesa.Valor }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2">Nenhuma despesa encontrada.</td>
            </tr>
            {% endfor %}
        </table>


        <div style="margin-top: 60px; margin-bottom: 20px;">
            <a href="{% url 'polls:listarbalancetes' %}" style="text-decoration: none; color: rgb(238, 255, 0); 
            background-color: blueviolet; padding: 10px; 
            border: 2px solid rgb(238, 255, 0); border-radius: 5px;">Voltar à lista</a>

        </div>
    </div>
</body>

</html>